apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: VG9rZW5Ub2tlblRva2VuVG9rZW5NYWxrb3ZpY2hUb2tlbg==
  AUTH_GITHUB_CLIENT_ID: SXYxLmE1OThlNGNjNTUyMWQwMWE=
  AUTH_GITHUB_CLIENT_SECRET: MTA4N2E0MzQxNjFkN2U3ZTM4OGFiMzgxNGQ2MjhiMDc3NmU0ZDdjMw==
