apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - pods
      - secrets
      - services
      - nodes
      - endpoints
    verbs:
      - get
      - list
      - watch
  # ... additional rules here ...